-- Drop the translations table if it exists
DROP TABLE IF EXISTS translations;

-- Create translations table
CREATE TABLE translations (
    id SERIAL PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL
);

-- Insert translations
INSERT INTO translations (key, value) VALUES
('admin.translations.addTitle', 'إضافة ترجمة جديدة'),
('admin.translations.add', 'إضافة'),
('admin.translations.adding', 'جاري الإضافة...'),
('admin.translations.addSuccess', 'تمت إضافة الترجمة بنجاح'),
('admin.translations.addError', 'فشل في إضافة الترجمة'),
('admin.translations.searchPlaceholder', 'ابحث في الترجمات...'),
('admin.translations.allLanguages', 'كل اللغات'),
('admin.translations.english', 'الإنجليزية'),
('admin.translations.arabic', 'العربية'),
('admin.translations.filterByLanguage', 'تصفية حسب اللغة'),
('admin.translations.selectLanguage', 'اختر اللغة'),
('common.storeName', 'أزهار ستور'),
('common.cart', 'السلة'),
('common.searchPlaceholder', 'البحث في المنتجات...'),
('common.noProducts', 'لا توجد منتجات'),
('common.footer', '© 2025 أزهار ستور. جميع الحقوق محفوظة.'),
('common.toggleSidebar', 'طي القائمة'),
('Login', 'تسجيل الدخول'),
('Logout', 'تسجيل الخروج'),
('Dashboard', 'لوحة التحكم'),
('Products', 'المنتجات'),
('Categories', 'الفئات'),
('Admin Panel', 'لوحة الإدارة'),
('common.search', 'بحث'),
('common.save', 'حفظ'),
('common.cancel', 'إلغاء'),
('common.delete', 'حذف'),
('common.edit', 'تعديل'),
('common.add', 'إضافة'),
('common.confirm', 'تأكيد'),
('common.create', 'إنشاء'),
('common.saveChanges', 'حفظ التغييرات'),
('common.actions', 'الإجراءات'),
('common.currency', 'د.ب'),
('common.notAvailable', 'غير متوفر'),
('common.allCategories', 'جميع الفئات'),
('common.filterByCategory', 'التصفية حسب الفئة'),
('common.allCustomers', 'جميع العملاء'),
('common.filterByCustomer', 'التصفية حسب العميل'),
('common.allProducts', 'جميع المنتجات'),
('common.filterByProduct', 'التصفية حسب المنتج'),
('common.productsWithOrders', 'المنتجات المطلوبة'),
('common.productsWithoutOrders', 'المنتجات غير المطلوبة'),
('common.filterByOrders', 'التصفية حسب الطلبات'),
('settings.title', 'الإعدادات'),
('settings.deliverySettings', 'إعدادات التوصيل'),
('settings.freeDeliveryThreshold', 'الحد الأدنى للتوصيل المجاني'),
('settings.deliveryAreas', 'مناطق التوصيل'),
('settings.addArea', 'إضافة منطقة'),
('settings.editArea', 'تعديل منطقة'),
('settings.areaName', 'اسم المنطقة'),
('settings.deliveryPrice', 'سعر التوصيل'),
('settings.confirmDeleteArea', 'هل أنت متأكد من حذف منطقة التوصيل هذه؟'),
('settings.deliveryArea', 'منطقة التوصيل'),
('settings.selectArea', 'اختر منطقة'),
('settings.delivery', 'التوصيل'),
('settings.messages', 'الرسائل'),
('settings.deliveryMessage', 'رسالة التوصيل'),
('settings.pickupMessage', 'رسالة الاستلام'),
('settings.areaUpdatedSuccess', 'تم تحديث المنطقة بنجاح'),
('settings.areaAddedSuccess', 'تم إضافة المنطقة بنجاح'),
('settings.areaSaveError', 'فشل في حفظ المنطقة'),
('settings.areaDeletedSuccess', 'تم حذف المنطقة بنجاح'),
('settings.areaDeleteError', 'فشل في حذف المنطقة'),
('settings.deliverySettingsSaved', 'تم حفظ إعدادات التوصيل'),
('settings.deliverySettingsError', 'فشل في حفظ إعدادات التوصيل'),
('settings.messagesSaved', 'تم حفظ الرسائل'),
('settings.messagesError', 'فشل في حفظ الرسائل'),
('productManagement.title', 'إدارة المنتجات'),
('productManagement.addProduct', 'إضافة منتج'),
('productManagement.editProduct', 'تعديل منتج'),
('productManagement.confirmDelete', 'هل أنت متأكد من حذف هذا المنتج؟'),
('productManagement.form.name', 'اسم المنتج'),
('productManagement.form.description', 'الوصف'),
('productManagement.form.price', 'السعر'),
('productManagement.form.category', 'الفئة'),
('productManagement.form.selectCategory', 'اختر فئة'),
('productManagement.form.stock', 'الكمية'),
('productManagement.form.images', 'الصور'),
('productManagement.form.primaryImage', 'الصورة الأساسية'),
('productManagement.form.galleryImages', 'صور المعرض'),
('productManagement.form.image', 'الصورة'),
('productManagement.form.variants', 'الخيارات'),
('productManagement.form.addVariant', 'إضافة خيار'),
('productManagement.form.variantName', 'اسم الخيار'),
('productManagement.form.totalStock', 'إجمالي المخزون'),
('productManagement.form.imagesSelected', '{{count}} صور مختارة'),
('productManagement.form.clickToUpload', 'انقر لتحميل الصور'),
('productManagement.form.draftName', 'منتج جديد (مسودة)'),
('productManagement.form.downloadAll', 'تحميل الكل'),
('productManagement.imageAlt', 'صورة المنتج'),
('productManagement.primaryBadge', 'الأساسية'),
('productManagement.tooltips.viewImage', 'عرض الصورة'),
('productManagement.tooltips.setAsPrimary', 'تعيين كأساسية'),
('productManagement.tooltips.downloadImage', 'تحميل الصورة'),
('productManagement.tooltips.removeImage', 'إزالة الصورة'),
('productManagement.actions.view', 'عرض'),
('productManagement.actions.setAsPrimary', 'تعيين كأساسية'),
('productManagement.actions.download', 'تحميل'),
('productManagement.actions.remove', 'إزالة'),
('productManagement.imagePreview', 'معاينة الصورة'),
('productManagement.tabs.details', 'التفاصيل'),
('productManagement.tabs.images', 'الصور'),
('productManagement.tabs.variants', 'الخيارات'),
('productManagement.saving', 'جاري الحفظ...'),
('productManagement.uploadingImages', 'جاري رفع الصور...'),
('productManagement.errors.fetch', 'فشل في تحميل المنتجات'),
('productManagement.errors.add', 'فشل في إضافة المنتج'),
('productManagement.errors.update', 'فشل في تحديث المنتج'),
('productManagement.errors.delete', 'فشل في حذف المنتج'),
('productManagement.errors.draftError', 'فشل في إنشاء مسودة المنتج'),
('productManagement.errors.uploadError', 'فشل في تحميل الصور'),
('productManagement.errors.addVariantError', 'فشل في إضافة الخيار'),
('productManagement.errors.updateVariantError', 'فشل في تحديث الخيار'),
('productManagement.errors.variantInUse', 'لا يمكن حذف الخيار لأنه مستخدم في طلب حالي.'),
('productManagement.errors.saveVariantFirst', 'يرجى حفظ الخيار أولاً'),
('productManagement.errors.variantNameRequired', 'اسم الخيار مطلوب'),
('productManagement.errors.downloadFailed', 'فشل التحميل'),
('productManagement.errors.noImagesToDownload', 'لا توجد صور للتحميل'),
('productManagement.errors.unexpected', 'حدث خطأ غير متوقع'),
('productManagement.notifications.productAdded', 'تم إضافة المنتج بنجاح'),
('productManagement.notifications.productUpdated', 'تم تحديث المنتج بنجاح'),
('productManagement.notifications.productDeleted', 'تم حذف المنتج بنجاح'),
('productManagement.notifications.variantAdded', 'تم إضافة الخيار بنجاح'),
('productManagement.notifications.variantUpdated', 'تم تحديث الخيار بنجاح'),
('productManagement.notifications.variantImageUploaded', 'تم رفع صورة الخيار بنجاح'),
('categoryManagement.title', 'إدارة الفئات'),
('categoryManagement.addCategory', 'إضافة فئة'),
('categoryManagement.editCategory', 'تعديل فئة'),
('categoryManagement.confirmDelete', 'هل أنت متأكد من حذف هذه الفئة؟'),
('categoryManagement.form.name', 'اسم الفئة'),
('categoryManagement.errors.fetch', 'فشل في تحميل الفئات'),
('categoryManagement.errors.add', 'فشل في إضافة الفئة'),
('categoryManagement.errors.update', 'فشل في تحديث الفئة'),
('categoryManagement.errors.delete', 'فشل في حذف الفئة'),
('categoryManagement.notifications.added', 'تم إضافة الفئة بنجاح'),
('categoryManagement.notifications.updated', 'تم تحديث الفئة بنجاح'),
('categoryManagement.notifications.deleted', 'تم حذف الفئة بنجاح'),
('admin.nav.products', 'المنتجات'),
('admin.nav.categories', 'الفئات'),
('admin.nav.customers', 'العملاء'),
('admin.nav.home', 'الرئيسية'),
('admin.nav.translations', 'الترجمات'),
('admin.translations.title', 'الترجمات'),
('admin.translations.loading', 'جاري تحميل الترجمات...'),
('admin.translations.key', 'المفتاح'),
('admin.translations.value', 'القيمة'),
('admin.translations.edit', 'تعديل'),
('admin.translations.editTitle', 'تعديل الترجمة'),
('admin.translations.save', 'حفظ'),
('admin.translations.saving', 'جاري الحفظ...'),
('admin.translations.cancel', 'إلغاء'),
('admin.translations.updateSuccess', 'تم تحديث الترجمة بنجاح'),
('admin.translations.updateError', 'فشل في تحديث الترجمة'),
('customerManagement.title', 'إدارة العملاء'),
('customerManagement.addCustomer', 'إضافة عميل'),
('customerManagement.editCustomer', 'تعديل عميل'),
('customerManagement.confirmDelete', 'هل أنت متأكد من حذف هذا العميل؟'),
('customerManagement.table.name', 'الاسم'),
('customerManagement.table.phone', 'رقم الهاتف'),
('customerManagement.table.town', 'المدينة'),
('customerManagement.table.address', 'العنوان'),
('customerManagement.form.name', 'الاسم'),
('customerManagement.form.phone', 'رقم الهاتف'),
('customerManagement.form.town', 'المدينة'),
('customerManagement.form.addressHome', 'المنزل'),
('customerManagement.form.addressRoad', 'الطريق'),
('customerManagement.form.addressBlock', 'المجمع'),
('customerManagement.form.address', 'العنوان'),
('customerManagement.form.phoneHint', 'يجب أن يتكون رقم الهاتف من 8 أرقام'),
('customerManagement.form.phoneValidationError', 'لم يستوفِ رقم الهاتف متطلبات الطول'),
('customerManagement.errors.fetch', 'فشل في تحميل العملاء'),
('customerManagement.errors.submit', 'فشل في حفظ العميل'),
('customerManagement.errors.delete', 'فشل في حذف العميل'),
('customerManagement.notifications.added', 'تم إضافة العميل بنجاح'),
('customerManagement.notifications.updated', 'تم تحديث العميل بنجاح'),
('customerManagement.notifications.deleted', 'تم حذف العميل بنجاح'),
('orderManagement.title', 'إدارة الطلبات'),
('orderManagement.addOrder', 'إضافة طلب'),
('orderManagement.editOrder', 'تعديل طلب'),
('orderManagement.confirmDelete', 'هل أنت متأكد من حذف هذا الطلب؟'),
('orderManagement.table.orderId', 'رقم الطلب'),
('orderManagement.table.customer', 'العميل'),
('orderManagement.table.status', 'الحالة'),
('orderManagement.table.shippingMethod', 'طريقة الشحن'),
('orderManagement.table.total', 'المجموع'),
('orderManagement.table.date', 'التاريخ'),
('orderManagement.form.customer', 'العميل'),
('orderManagement.form.selectCustomer', 'اختر عميل'),
('orderManagement.form.products', 'المنتجات'),
('orderManagement.form.addProduct', 'إضافة منتج'),
('orderManagement.form.shippingMethod', 'طريقة الشحن'),
('orderManagement.form.selectShippingMethod', 'اختر طريقة الشحن'),
('orderManagement.form.status', 'الحالة'),
('orderManagement.form.selectStatus', 'اختر الحالة'),
('orderManagement.form.comments', 'ملاحظات'),
('orderManagement.form.orderItems', 'عناصر الطلب'),
('orderManagement.form.noVariants', 'لا توجد خيارات'),
('orderManagement.form.selectProduct', 'اختر منتج'),
('orderManagement.form.selectVariant', 'اختر خيار'),
('orderManagement.form.productNotFound', 'المنتج غير موجود'),
('orderManagement.form.total', 'المجموع'),
('orderManagement.form.subtotal', 'المجموع الفرعي'),
('orderManagement.form.freeDeliveryApplied', 'تم تطبيق التوصيل المجاني'),
('orderManagement.form.unitPrice', 'سعر الوحدة'),
('orderManagement.form.quantity', 'الكمية'),
('orderManagement.freeDeliveryApplied', 'تم تطبيق التوصيل المجاني'),
('orderManagement.status.processing', 'قيد المعالجة'),
('orderManagement.status.ready', 'جاهز'),
('orderManagement.status.shipped', 'تم الشحن'),
('orderManagement.status.delivered', 'تم التوصيل'),
('orderManagement.status.cancelled', 'تم الإلغاء'),
('orderManagement.shipping.delivery', 'توصيل'),
('orderManagement.shipping.pick_up', 'استلام'),
('orderManagement.errors.fetch', 'فشل في تحميل الطلبات'),
('orderManagement.errors.submit', 'فشل في حفظ الطلب'),
('orderManagement.errors.freeDeliveryApplied', 'تم تطبيق التوصيل المجاني');
